#if !canImport(ObjectiveC)
import XCTest

extension swiftMetalPlatformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__swiftMetalPlatformTests = [
        ("testMetalCreateSystemDefaultDevice", testMetalCreateSystemDefaultDevice),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(swiftMetalPlatformTests.__allTests__swiftMetalPlatformTests),
    ]
}
#endif
